# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setForSummer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
