# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setForSummer_app', '0003_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=5)),
                ('relationship', models.CharField(max_length=255)),
                ('newsletter', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('activities', models.BooleanField(default=False)),
                ('learning', models.BooleanField(default=False)),
            ],
        ),
    ]
